### ISSUE TITLE
files option doesn't work as expected?

### ISSUE THREAD

**Issue by tuananh** [OverZealous/cdnizer#30]
i have this manifest.json like this

```
<link rel="manifest" href="/assets/manifest.json">
```

after enable cdnizer, i got

    <link rel="manifest" href="//mycdn.com/assets/manifest.json">

even though i already set `files` in cdnizer options to be like below: only css/js and images

```
{
              defaultCDNBase: '//mycdn.com',
              files: ['**/*.{css,js,svg,gif,png,jpg,jpeg}']
            },
```

**Comment by OverZealous** [comment]
I'm assuming it's matching because `**/*.js` effectively expands to something like `/.*\.js/`, which is matching anything that has `.js` in it.

This is related to using globbing for the matches.

The best bet here is to be more specific in your matcher(s), and include some path information. You'll not only will avoid this issue (and other unexpected issues), the matchers won't have to work as hard.

I generally don't recommend generic globbing.

**Comment by tuananh** [comment]
@OverZealous i change it to be `files: ['**/*{chunk,bundle}*.{css,js}']` which should not match `manifest.json` but it's still change. Any idea?

**Comment by tuananh** [comment]
@OverZealous seems to be issue with the plugin that make use of cdnizer. Thank you for your support.
